version: '3'

services:

    cictio_mysql:
        image: mysql:latest
        restart: always
        ports:
            - 3306:33060
        environment:
            - MYSQL_ROOT_PASSWORD=cictio
            - MYSQL_USER=cictio_user
            - MYSQL_PASSWORD=cictio
            - MYSQL_DATABASE=cictio_db
        
        volumes:
            - cictio-db:/var/lib/mysql
            - ./ORM/db.sql:/docker-entrypoint-initdb.d/db_schema.sql

        networks:
            - mysql-network

    cictio_server: 

        #image: luisny/cictio-server:1.0
        build: .

        links:
            - cictio_mysql
        ports:
            - 0.0.0.0:8080:8081
        depends_on: 
            - cictio_mysql # This service depends on cictio_mysql. Start that first.
        networks:
            - mysql-network

        stdin_open: true
        tty: true
            
volumes:
    cictio-db: 
        driver: local

networks:
    mysql-network:
        driver: bridge
